const info = [
    {
        id: 1,
        title: "Kimetsu No Yaiba",
        rating: "8.6",
        type: "TV Series",
        duration: "63 Episodes",
        time: "April 6, 2019 year",
        status: "Ongoing",
        author: "Koyoharu Gotouge",
        studio: "ufotable",
        alternative: "鬼滅の刃",
        cover: "covers/kimetsuSeries.jpg",
        video: "ramen.mp4",
    },
    {
        id: 2,
        title: "Kaoru Hana Wa Rin To Saku",
        rating: "8.4",
        type: "TV Series",
        duration: "13 Episodes",
        time: "July 6, 2025 year",
        status: "Ongoing",
        author: "Saka Mikami",
        studio: "CloverWorks",
        alternative: "薫る花は凛と咲く",
        cover: "covers/kaoru.jpg",
        video: "ramen.mp4",
    },
    {
        id: 3,
        title: "Cyberpunk",
        rating: "8.3",
        type: "TV Series",
        duration: "10 Episodes",
        time: "September 13, 2022 year",
        status: "Ongoing",
        author: "Studio Trigger и CD Projekt Red",
        studio: "Trigger",
        alternative: "サイバーパンク エッジランナーズ",
        cover: "covers/cyberpunk.jpg",
        video: "ramen.mp4",
    },
    {
        id: 4,
        title: "Sousou No Friren",
        rating: "8.9",
        type: "TV Series",
        duration: "28 Episodes",
        time: "September 29, 2023 year",
        status: "Ongoing",
        author: "Kanehito Yamada",
        studio: "Madhouse",
        alternative: "葬送のフリーレン",
        cover: "covers/frieren.jpg",
        video: "ramen.mp4",
    },
    {
        id: 5,
        title: "Jujutsu Kaisen",
        rating: "8.5",
        type: "TV Series",
        duration: "47 Episodes",
        time: "October 3, 2020 year",
        status: "Ongoing",
        author: "Gege Akutami",
        studio: "MAPPA",
        alternative: "呪術廻戦",
        cover: "covers/jujutsu.jpg",
        video: "ramen.mp4",
    },
    {
        id: 6,
        title: "Vinland Saga",
        rating: "8.8",
        type: "TV Series",
        duration: "48 Episodes",
        time: "July 8, 2019 year",
        status: "Finished",
        author: "Makoto Yukimura",
        studio: "Wit Studio",
        alternative: "ヴィンランド・サガ",
        cover: "covers/vinland.jpg",
        video: "ramen.mp4",
    },
    {
        id: 7,
        title: "Kusuriya no Hitorigoto",
        rating: "8.6",
        type: "TV Series",
        duration: "48 Episodes",
        time: "October 22, 2023 year",
        status: "Ongoing",
        author: "Natsu Hyuuga",
        studio: "OLM, TOHO animation STUDIO",
        alternative: "薬屋のひとりごと",
        cover: "covers/monolog.jpg",
        video: "ramen.mp4",
    },
    {
        id: 8,
        title: "One Piece",
        rating: "9.1",
        type: "TV Series",
        duration: "1155 Episodes",
        time: "October 20, 1999 year",
        status: "Ongoing",
        author: "Eiichiro Oda",
        studio: "Toei Animation",
        alternative: "ワンピース",
        cover: "covers/onepiece.jpg",
        video: "ramen.mp4",
    },
    {
        id: 9,
        title: "Jigokuraku",
        rating: "8.1",
        type: "TV Series",
        duration: "13 Episodes",
        time: "April 1, 2023 year",
        status: "Ongoing",
        author: "Yuuji Kaku",
        studio: "MAPPA",
        alternative: "地獄楽",
        cover: "covers/jigoraku.png",
        video: "ramen.mp4",
    },
    {
        id: 10,
        title: "Death Note",
        rating: "8.9",
        type: "TV Series",
        duration: "37 Episodes",
        time: "October 4, 2006 year",
        status: "Finished",
        author: "Tsugumi Ohba",
        studio: "Madhouse",
        alternative: "デスノート",
        cover: "covers/deathnote.jpg",
        video: "ramen.mp4",
    },
    {
        id: 11,
        title: "Attack On Titan",
        rating: "9.1",
        type: "TV Series",
        duration: "89 Episodes",
        time: "April 7, 2013 year",
        status: "Finished",
        author: "Hajime Isayama",
        studio: "Wit Studio",
        alternative: "進撃の巨人",
        cover: "covers/atakatitanov.jpg",
        video: "ramen.mp4",
    },
    {
        id: 12,
        title: "Hunter x Hunter",
        rating: "9.1",
        type: "TV Series",
        duration: "148 Episodes",
        time: "October 2, 2011 year",
        status: "Finished",
        author: "Yoshihiro Togashi",
        studio: "Madhouse",
        alternative: "ハンター×ハンター",
        cover: "covers/hunterXhunter.jpg",
        video: "ramen.mp4",
    },
    // xsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
    {
        id: 13,
        title: "Kimetsu no Yaiba Movie 1: Mugenjou-hen - Akaza Sairai",
        rating: "8.4",
        type: "Movie",
        duration: "2h 35m",
        time: "July 18, 2025 year",
        status: "Finished",
        author: "Koyoharu Gotouge",
        studio: "ufotable",
        alternative: "劇場版 鬼滅の刃 無限城編",
        cover: "covers/kimetsu.jpg",
        video: "ramen.mp4",
    },
    {
        id: 14,
        title: "Violet Evergarden Movie",
        rating: "8.3",
        type: "Movie",
        duration: "2h 20m",
        time: "September 18, 2020 year",
        status: "Finished",
        author: "Kana Akatsuki",
        studio: "Kyoto Animation",
        alternative: "劇場版 ヴァイオレット・エヴァーガーデン",
        cover: "covers/vayolet.jpg",
        video: "ramen.mp4",
    },
    {
        id: 15,
        title: "Akira",
        rating: "8.0",
        type: "Movie",
        duration: "2h 04m",
        time: "July 16, 1988 year",
        status: "Finished",
        author: "Katsuhiro Otomo",
        studio: "Tokyo Movie Shinsha",
        alternative: "アキラ",
        cover: "covers/akira.jpg",
        video: "ramen.mp4",
    },
    {
        id: 16,
        title: "Mononoke Hime",
        rating: "8.3",
        type: "Movie",
        duration: "2h 13m",
        time: "July 12, 1997 year",
        status: "Finished",
        author: "Hayao Miyazaki",
        studio: "Studio Ghibli",
        alternative: "もののけ姫",
        cover: "covers/mononoke.jpg",
        video: "ramen.mp4",
    },
    {
        id: 17,
        title: "Silent Voice",
        rating: "8.2",
        type: "Movie",
        duration: "2h 10m",
        time: "September 17, 2016 year",
        status: "Finished",
        author: "Yoshitoki Ooima",
        studio: "Kyoto Animation",
        alternative: "聲の形",
        cover: "covers/koe.jpg",
        video: "ramen.mp4",
    },
    {
        id: 18,
        title: "Spirited Away",
        rating: "8.6",
        type: "Movie",
        duration: "2h 04m",
        time: "July 20, 2001 year",
        status: "Finished",
        author: "Hayao Miyazaki",
        studio: "Studio Ghibli",
        alternative: "千と千尋の神隠し",
        cover: "covers/Spirited.jpg",
        video: "ramen.mp4",
    },
    {
        id: 19,
        title: "Your Name.",
        rating: "8.4",
        type: "Movie",
        duration: "1h 46m",
        time: "Avgust 26, 2016 year",
        status: "Finished",
        author: "Makoto Shinkai",
        studio: "CoMix Wave Films",
        alternative: "君の名は。",
        cover: "covers/yourname.jpg",
        video: "ramen.mp4",
    },
    {
        id: 20,
        title: "Jujutsu Kaisen 0 Movie",
        rating: "7.8",
        type: "Movie",
        duration: "1h 44m",
        time: "December 24, 2021 year",
        status: "Finished",
        author: "Gege Akutami",
        studio: "MAPPA",
        alternative: "劇場版 呪術廻戦 0",
        cover: "covers/jujutsufilm0.jpg",
        video: "ramen.mp4",
    },
    {
        id: 21,
        title: "Suzume no Tojimari",
        rating: "7.6",
        type: "Movie",
        duration: "2h 01m",
        time: "November 11, 2022 year",
        status: "Finished",
        author: "Makoto Shinkaii",
        studio: "CoMix Wave Films",
        alternative: "すずめの戸締まり",
        cover: "covers/suzume.jpg",
        video: "ramen.mp4",
    },
    {
        id: 22,
        title: "No Game No Life: Zero",
        rating: "7.3",
        type: "Movie",
        duration: "1h 46m",
        time: "July 15, 2017 year",
        status: "Finished",
        author: "Yuu Kamiya",
        studio: "Madhouse",
        alternative: "ノーゲーム・ノーライフ ゼロ",
        cover: "covers/nogamenolife.jpg",
        video: "ramen.mp4",
    },
    {
        id: 23,
        title: "Hotaru no Haka",
        rating: "8.5",
        type: "Movie",
        duration: "1h 28m",
        time: "April 16, 1988 year",
        status: "Finished",
        author: "Hayao Miyazaki",
        studio: "Studio Ghibli",
        alternative: "火垂るの墓",
        cover: "covers/hotaru.jpg",
        video: "ramen.mp4",
    },
    {
        id: 24,
        title: "Howl's Moving Castle",
        rating: "8.2",
        type: "Movie",
        duration: "1h 59m",
        time: "November 20, 2004 year",
        status: "Finished",
        author: "Diana Wynne Jones",
        studio: "Studio Ghibli",
        alternative: "ハウルの動く城",
        cover: "covers/Castle.jpg",
        video: "ramen.mp4",
    },
];
